# Configuração Global do Telegraf
[agent]
  interval = "10s"
  flush_interval = "10s"

# --- INPUT: De onde os dados vêm ---
[[inputs.mqtt_consumer]]
  # Endereço do seu Mosquitto
  servers = ["tcp://127.0.0.1:1883"]
  
  # O "tópico" que o Telegraf vai "escutar"
  topics = [
    "tcc/pzem/data"
  ]

  # Como os dados vão chegar: JSON
  data_format = "json"
  
  # O nome da "tabela" (measurement)
  name_override = "pzem_data"

  # --- USUÁRIO E SENHA MQTT ---
  username = "pfeuser"
  password = "pfeiot"
  # ----------------------------

# --- OUTPUT: Para onde os dados vão ---
[[outputs.influxdb_v2]]
  # Endereço do seu InfluxDB
  urls = ["http://127.0.0.1:8086"]

  # O Token de acesso do InfluxDB
  token = "SEU_TOKEN_DO_INFLUXDB_VAI_AQUI"

  # Os nomes que você definiu no setup do InfluxDB
  organization = "EngEletrica"
  bucket = "sensor_pzem"